[shell]
program = "Arch.exe"

[window]
opacity = 1.0

[bell]
command = "None"
duration = 0

[colors]
transparent_background_colors = false

[font]
size = 9

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"
